// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "realworld-aws-lambda-dynamodb-golang/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockFeedServiceInterface is an autogenerated mock type for the FeedServiceInterface type
type MockFeedServiceInterface struct {
	mock.Mock
}

type MockFeedServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeedServiceInterface) EXPECT() *MockFeedServiceInterface_Expecter {
	return &MockFeedServiceInterface_Expecter{mock: &_m.Mock}
}

// FanoutArticle provides a mock function with given fields: ctx, articleId, authorId, createdAt
func (_m *MockFeedServiceInterface) FanoutArticle(ctx context.Context, articleId uuid.UUID, authorId uuid.UUID, createdAt time.Time) error {
	ret := _m.Called(ctx, articleId, authorId, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for FanoutArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, articleId, authorId, createdAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeedServiceInterface_FanoutArticle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FanoutArticle'
type MockFeedServiceInterface_FanoutArticle_Call struct {
	*mock.Call
}

// FanoutArticle is a helper method to define mock.On call
//   - ctx context.Context
//   - articleId uuid.UUID
//   - authorId uuid.UUID
//   - createdAt time.Time
func (_e *MockFeedServiceInterface_Expecter) FanoutArticle(ctx interface{}, articleId interface{}, authorId interface{}, createdAt interface{}) *MockFeedServiceInterface_FanoutArticle_Call {
	return &MockFeedServiceInterface_FanoutArticle_Call{Call: _e.mock.On("FanoutArticle", ctx, articleId, authorId, createdAt)}
}

func (_c *MockFeedServiceInterface_FanoutArticle_Call) Run(run func(ctx context.Context, articleId uuid.UUID, authorId uuid.UUID, createdAt time.Time)) *MockFeedServiceInterface_FanoutArticle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(time.Time))
	})
	return _c
}

func (_c *MockFeedServiceInterface_FanoutArticle_Call) Return(_a0 error) *MockFeedServiceInterface_FanoutArticle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeedServiceInterface_FanoutArticle_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, time.Time) error) *MockFeedServiceInterface_FanoutArticle_Call {
	_c.Call.Return(run)
	return _c
}

// FetchArticlesFromFeed provides a mock function with given fields: ctx, userId, limit, nextPageToken
func (_m *MockFeedServiceInterface) FetchArticlesFromFeed(ctx context.Context, userId uuid.UUID, limit int, nextPageToken *string) ([]domain.FeedItem, *string, error) {
	ret := _m.Called(ctx, userId, limit, nextPageToken)

	if len(ret) == 0 {
		panic("no return value specified for FetchArticlesFromFeed")
	}

	var r0 []domain.FeedItem
	var r1 *string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, *string) ([]domain.FeedItem, *string, error)); ok {
		return rf(ctx, userId, limit, nextPageToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, *string) []domain.FeedItem); ok {
		r0 = rf(ctx, userId, limit, nextPageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FeedItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, *string) *string); ok {
		r1 = rf(ctx, userId, limit, nextPageToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, *string) error); ok {
		r2 = rf(ctx, userId, limit, nextPageToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFeedServiceInterface_FetchArticlesFromFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchArticlesFromFeed'
type MockFeedServiceInterface_FetchArticlesFromFeed_Call struct {
	*mock.Call
}

// FetchArticlesFromFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
//   - limit int
//   - nextPageToken *string
func (_e *MockFeedServiceInterface_Expecter) FetchArticlesFromFeed(ctx interface{}, userId interface{}, limit interface{}, nextPageToken interface{}) *MockFeedServiceInterface_FetchArticlesFromFeed_Call {
	return &MockFeedServiceInterface_FetchArticlesFromFeed_Call{Call: _e.mock.On("FetchArticlesFromFeed", ctx, userId, limit, nextPageToken)}
}

func (_c *MockFeedServiceInterface_FetchArticlesFromFeed_Call) Run(run func(ctx context.Context, userId uuid.UUID, limit int, nextPageToken *string)) *MockFeedServiceInterface_FetchArticlesFromFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(*string))
	})
	return _c
}

func (_c *MockFeedServiceInterface_FetchArticlesFromFeed_Call) Return(_a0 []domain.FeedItem, _a1 *string, _a2 error) *MockFeedServiceInterface_FetchArticlesFromFeed_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFeedServiceInterface_FetchArticlesFromFeed_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, *string) ([]domain.FeedItem, *string, error)) *MockFeedServiceInterface_FetchArticlesFromFeed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeedServiceInterface creates a new instance of MockFeedServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeedServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeedServiceInterface {
	mock := &MockFeedServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
